In [ ]:
import numpy as np
import pandas as pd

data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]]) # Create a 5x2 table
column_names = ['temperature', 'activity'] # Create labels for the 2 columns
df = pd.DataFrame(data=data, columns=column_names)

#Add new columns to the dataframe
df['adjusted'] = df['activity'] + 2
print(df)

temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17

In [ ]:
# Specify a subset of a dataframe
print("Rows #0, #1, and #2:")
print(df.head(3), '\n')

print("Row #2:")
print(df.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(df[1:4], '\n')

print("Temperature Column:")
print(df['temperature'])

Rows #0, #1, and #2:
   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11

Row #2:
   temperature  activity  adjusted
2           20         9        11

Rows #1, #2, and #3:
   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16

Temperature Column:
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int32

In [ ]:
#1. Create a 3x4  dataframe with columns 'Elenaor', 'Chidi', 'Tahani', 'Jason' and each 12
# cells should have a random int between 1 and 100
me_data = np.random.randint(low=1, high=101, size=(3, 4))
column_name = ['Elenaor', 'Chidi', 'Tahani', 'Jason']
df2 = pd.DataFrame(data=me_data, columns=column_name)

#2.Output the entire dataframe and Row #1 of Column 'Elenaor'
print("Entire Dataframe:")
print(df2, '\n')

print("Elenoar's Row 1:")
print(df2['Elenaor'][1], '\n')

# 3. Create a fith column named 'Janet' where row values would be the sum of 'Tahani' and 'Jason'
df2['Janet'] = df2['Tahani'] + df2['Jason']
print("Dataframe with 5th column:")
print(df2)

Entire Dataframe:
   Elenaor  Chidi  Tahani  Jason
0       24     97      64     94
1       26     90      38     97
2       55     27      75     73

Elenoar's Row 1:
26

Dataframe with 5th column:
   Elenaor  Chidi  Tahani  Jason  Janet
0       24     97      64     94    158
1       26     90      38     97    135
2       55     27      75     73    148

In [ ]:
# Copying a Dataframe
# Method 1, Referencing a dataframe which would be dependent on the original

# Creating referenced
referenced = df2
print("Reference Example:")
print(" Starting value of df: ", df2['Jason'][1])
print(" Starting value of refercned: ", referenced['Jason'][1])

# Updating only the df value
df2.at[1, 'Jason'] = df2['Jason'][1] + 5
print(" Updated value of df:", df2['Jason'][1])
print(" Updated value of referenced: ", referenced['Jason'][1], '\n')

# Method 2, Creating a indepentdent copy of the original
copy = df2.copy()
print("Independent Exmaple: ")
print(" Starting value of df: ", df2['Jason'][1])
print(" Starting value of copy: ", copy['Jason'][1])

# Updating only the df value
df2.at[1, 'Jason'] = df2['Jason'][1] + 3
print(" Updated value of df: ", df2['Jason'][1])
print(" Copy value of df: ", copy['Jason'][1])

Reference Example:
 Starting value of df:  107
 Starting value of refercned:  107
 Updated value of df: 112
 Updated value of referenced:  112

Independent Exmaple:
 Starting value of df:  112
 Starting value of copy:  112
 Updated value of df:  115
 Copy value of df:  112